server:
  port: 8801

spring:
  datasource:
    name: pay_db
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://127.0.0.1:3306/pay_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  freemarker:
    template-loader-path: classpath:/templates/  #模板的位置 这里是在resources/templates下*/
    request-context-attribute: req
    cache: false
    enabled: true
    allow-request-override: false
    check-template-location: true
    content-type: text/html
    suffix: .html
    charset: UTF-8 #编码格式
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    settings:
      number_format: '0.##'   #数字格式化，无小数点
    # 修改默认的静态资源存放目录
  resources:
    static-locations: classpath:/static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fengdu.entity

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

